clear all;
clc;
%天线相关参数
a=linspace(0,2*pi);
b=linspace(0,2*pi);
[theta,phi]=meshgrid(a,b);
N=19;
%共同条件定义
lamda=100;%单位毫米
k=2*pi/lamda;%波传播常数
d=lamda/4;%单元间距
%归一化阵因子函数
s_S=sin(N/2*k*d.*cos(a))./(N.*sin(k*d.*cos(a)./2));%边射
s_E=sin(N/2*k*d.*(cos(a)+1))./(N.*sin(k/2*d.*(cos(a)+1)));%端射
s_DE=sin(pi/2/N).*sin(N/2.*(k*d.*(cos(a)+1)+pi/N))./sin(0.5.*(k*d.*(cos(a)+1)+pi/N));
%最大单元间距(波长的倍数)
dmax_S=(N-1)/N;%侧射
dmax_E=1/2*(1-1/2/N);%端射
dmax_DE=1/2*(1-1/N);%增强型端射阵
%增益
D_S=2*N*d/lamda;%边射
D_E=4*N*d/lamda;%端射
D_DE=7.22*N*d/lamda;%增强型端射
%零点波瓣宽度
BWnp1_S=2*(pi/2-acos(2*pi/N/k/d));
BWnp1_E=2*sqrt(2*lamda/N/d);
BWnp1_DE=2*acos(1-pi/N/k/d);
%半功率波瓣宽度
BWhp_S=0.886*lamda/N/d;
BWhp_E=2*sqrt(0.886*lamda/N/d);
BWhp_DE=2*sqrt(0.28*lamda/N/d);
%画图
subplot(2,2,1)
polar(a,s_S,'r');
title({'侧射阵极坐标方向图',['N=',num2str(N)]});
subplot(2,2,2)
polar(a,s_E,'r');
title({'端射阵阵极坐标方向图',['N=',num2str(N)]});
subplot(2,2,3)
polar(a,s_DE,'r');
title({'增强型端射阵极坐标方向图',['N=',num2str(N)]});